### PR TITLE
Adds data from the individual commit to an issue generation

### LINKED ISSUE #11: Include git commit details in an autogenerated issue

### PR DESCRIPTION
**Pull request by mitchellbusby**
Resolves #11 by adding data from the commit to the generated issue. See below for the format. 

screen shot 2016-06-03 at 5 05 38 pm

### CODE REVIEW

**Comment by PatMurrayDEV** [comment]
Nice one! Is there anyway to assign the issue to the person who made the commit?

**Comment by mitchellbusby** [comment]
@PatMurrayDEV I believe that is how the code has always worked

**Comment by PatMurrayDEV** [comment]
Hmm you sure? The assignee is a field that needs to be set, else no one is assigned to an issue (see issue #10 -- I just assigned it to me)

**Comment by mitchellbusby** [comment]
Oh, I misunderstood what you meant. My bad. Have not done that.

**Pull request merged**
